### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by BenSmith0** [FroastJ/roblox-bots#10]
https://github.com/FroastJ/roblox-bots/blob/master/Examples/receiver.php
I don't understand about GetKey and postkey
Where you get it from?
Alway get error from me. Is there a link to generate the code?

**Comment by NNickey** [comment]
You put your own getkey and postkey

**Comment by NNickey** [comment]
Just make it up. It can be something like 'kaskfk3kqk5ju' or 'gkqekuk345y7'
It's all up to you.

**Comment by BenSmith0** [comment]
FAILURE: Incorrect/missing validation key.

**Comment by NNickey** [comment]
Did you supply your get and post key in the URL and one in the HTTP POST?

**Comment by BenSmith0** [comment]
http://prntscr.com/9ktnbv In receiver.php? Wait Do I have to use roblox and run it? or something?

**Comment by NNickey** [comment]
yes, and did you give your bot url the get key?

website link / php file &get=stuff

and

post in your POST

On Thu, Dec 31, 2015 at 10:33 PM, unofficialROBLOX <notifications@github.com

**Comment by BenSmith0** [comment]
I got it working.
