### ISSUE TITLE
Error with the cookies

### ISSUE THREAD

**Issue by Zlecktov** [FroastJ/roblox-bots#13]
I find that whenever I open the cookietime.txt it is a random number

![image](https://cloud.githubusercontent.com/assets/17452673/13477172/ab76d3ac-e090-11e5-8f08-91eeeb2b9fd6.png)

This leads to a major issue as the cookie eventually expires and needs to be renewed.  If you have any clue on how to fix this and I did what you said in the previous issue

![image](https://cloud.githubusercontent.com/assets/17452673/13477211/e76006ae-e090-11e5-8e84-21c220977dc9.png)

Changed it to that and the problem persists.

**Comment by NNickey** [comment]
cookieTime.txt is the time that the cookie was made, not a random number. This is to compare it with the next time to save a new cookie in the folder Private which stores your true cookie.

EDIT: If you read on line `file_put_contents($cookieTime,time())`, it clearly shows that it's putting the current OS time in the variable to the file named cookieTime.txt.

Login is managed on the login function and manages the cookie separately on a different script.

**Comment by NNickey** [comment]
@Zlecktov You never said what the problem is? If you follow from top to bottom in the script, it already checks the current time against the cookieTime.txt which was the time the login to refresh a new cookie was made, so that it'll make a new cookie over time.

**Comment by Zlecktov** [comment]
The script is not renewing the cookie is my problem.

**Comment by NNickey** [comment]
The script is renewing your cookie, but you keep thinking cookieTime.txt is your cookie file, when it's not, and your true cookie file is in the Private folder.

**Comment by Zlecktov** [comment]
The script is not renewing my cookie as I keep having to delete my cookie and let it login in again.   I do not see how you think that isn't an error.  I understand what you are saying I re-read the code and get that time()-cookietime  yes I understand this.   I am saying that the script is failing to renew my cookie.

**Comment by sentanos** [comment]
Your issue is much too vague. I cannot reproduce it and there does not seem to be _any actual error_. I have reviewed the code itself and can find no logic errors. If I'm wrong on any of these please point it out. 

Please review your apache and PHP error logs and check for errors. If you find any, make a new issue that describes the problem and at least attempt to fix it yourself.

You are currently claiming there is some type of logic error without actually telling me what it is. Until you can introduce an actual issue, this one is closed.

**Comment by NNickey** [comment]
As I state one more time, the script IS renewing your cookie, but it doesn't renew it if the last cookie failed, of course. It expects you to at least not change your password and not to unlink from all devices.

**Comment by Zlecktov** [comment]
It seems that my error was my co-worker messing with the account.  I am sorry for wasting your time.
