### ISSUE TITLE
Join Request Bot doesn't accept user specified

### ISSUE THREAD

**Issue by SparkleOff** [FroastJ/roblox-bots#15]
It doesn't accept the specified user through the function. It only accepts the first person that sent the request out of all the others.

How i use the function:
handleJoinRequest($cookie,224398,"Bots","Accept");

(put random stuff in the fields to show just i how use the function.)

**Comment by sentanos** [comment]
The issue is related to yet another pointless change in ROBLOX's group admin API. I don't have time to adjust the PHP script right now but I will do so as soon as possible.

**Comment by SparkleOff** [comment]
Alright thanks and keep me updated on it if you can!

**Comment by AdamsBlack** [comment]
Any updates?

**Comment by sentanos** [comment]
Sorry, I kind of forgot about this, I'll work on it soon.

**Comment by sentanos** [comment]
Fixed in Commit 8c7a8a2, sorry I didn't do this sooner.

**Comment by AdamsBlack** [comment]
Thanks :)
