### ISSUE TITLE
Login errors?

### ISSUE THREAD

**Issue by LukeTechnoUserOfficial** [FroastJ/roblox-bots#17]
Hey,
I know this is a pretty vague issue. However, I've been reading through the readme files and they are not very clear. In the receiver.php, I changed my group ID as well as my get and post keys. I believe I had to change the 'username' and 'password' to my bot's account too. I then used the send.lua to send the player to the server and according to roblox it send back, but the player was not promoted at all.

I am using hostinate.com/ as a server and I have put this entire folder into the server. Is there anything else that I need to edit?

Thanks
Luke
![one](https://cloud.githubusercontent.com/assets/19302512/15175071/94019696-175c-11e6-9194-df64c226db01.png)
![two](https://cloud.githubusercontent.com/assets/19302512/15175070/9400f89e-175c-11e6-9fba-77c237a451fd.png)
[Receiver.txt](https://github.com/FroastJ/roblox-bots/files/258881/Receiver.txt)

**Comment by sentanos** [comment]
Your setup looks correct, I can't help you beyond that because you have not told me what actually happened with the request other than the fact that it didn't work.
- What was the exact message returned?
- If no message was returned, what is in your error log?

**Comment by LukeTechnoUserOfficial** [comment]
Oh i'm sorry! It's something to do with the 'getRoles.php
'Line 27'
Syntax Error unexpected '['
[getRoles.txt](https://github.com/FroastJ/roblox-bots/files/259049/getRoles.txt)

$roles = json_decode(file_get_contents("http://api.roblox.com/groups/$group"),true)['Roles'];

**Comment by sentanos** [comment]
That error is caused by an outdated PHP version that does not support newer syntax used in a script, specifically this line in `getRoles.php`:

``` php
$roles = json_decode(file_get_contents("http://api.roblox.com/groups/$group"),true)['Roles'];
```

If possible, upgrade your PHP version; however, this can be easily fixed by the line to:

``` php
$json = json_decode(file_get_contents("http://api.roblox.com/groups/$group"),true);
$roles = $json['Roles'];
```

I can't remember if this is the only syntax incompatibility with older PHP versions, but I'm pretty sure other than trivial syntax incompatibilities the scripts should work.

**Comment by LukeTechnoUserOfficial** [comment]
Okay now I have another error
line 31 login.php

**Comment by LukeTechnoUserOfficial** [comment]
Okay nvm that issue. 
I think I have the last and final issue.
Line 58 
changeRank.php

It's a json_decode, however i'm not sure how to implement it as what you explained at the top? Could you help me with that last bit?

**Comment by LukeTechnoUserOfficial** [comment]
This is my attempt? What did I do wrong?

<?php
	/*
	
	RankLimit can be used to restrict people from changing the rank of people who aren't a low rank.
	
	I'm also trying to not use globals because it's "good practice", so the function accepts !!*A LOT*!! of arguments.
	
	*/
	include_once 'Includes/http_parse_headers.php';
	include_once 'Includes/misc.php';
	function updateRank($group,$userId,$rank,$cookie,$ranks,$roles,$rankLimit=255,$save='./Private/gxcsrf.txt') { // OH MY GOD SO MANY ARGUMENTS!
		$xcsrf = file_exists($save) ? file_get_contents($save) : '';
		/* 
		
		If you want to increase performance do this:
			Move the following line (currentRank) into the rankLimit if statement.
			Change the success return to something simpler (does not return user's previous rank)
			
			This doesn't actually slow it down that much at all, but when changing ranks **IN BULK** you will be making a lot of requests.
			
		*/
		$currentRank = getRankInGroup($userId,$group);
		if ($rankLimit && $rankLimit < 255) {
			if ($rank > $rankLimit || $currentRank > $rankLimit) { // Check if the rank you are trying to change them to and their rank abide to the rank limit
				return "Settings restrict the system from changing any rank over $rankLimit.";
			}
		}
		$url = "http://www.roblox.com/groups/api/change-member-rank?groupId=$group&newRoleSetId=".getRoleSet($ranks,$rank)."&targetUserId=$userId"; // Get rank URL
		$curl = curl_init($url);
		curl_setopt_array($curl,array(
			CURLOPT_HEADER => true,
			CURLOPT_HTTPHEADER => array(                                                          
				"X-CSRF-TOKEN: $xcsrf",
				'Content-Length: 0' // Because it's required :\
			),
			CURLOPT_POST => true,
			CURLOPT_COOKIEFILE => $cookie,
			CURLOPT_COOKIEJAR => $cookie,
			CURLOPT_RETURNTRANSFER => true
		));
		$response = curl_exec($curl);
		$headerSize = curl_getinfo($curl,CURLINFO_HEADER_SIZE);
		$responseCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
		if ($responseCode != 200) {
			// BELOW 302 DOES NOT WORK AND IS DEPRACATED FOR NOW
			/*if ($responseCode == 302) { // 302 Moved temporarily - User is not logged in: Redirect to error page
				login($cookie,$username,$password);
				return updateRank($username,$password,$group,$userId,$rank,$cookie,$ranks,$roles,$rankLimit,$save); // Would appreciate if someone showed me a better way to do this (not repassing every argument manually).
			} else */if ($responseCode == 403) { // 403 XCSRF Token Validation Failed - CONVENIENCE!
				$header = http_parse_headers(substr($response,0,$headerSize));
				$xcsrf = $header['X-CSRF-TOKEN'];
				file_put_contents($save,$xcsrf);
				return updateRank($group,$userId,$rank,$cookie,$ranks,$roles,$rankLimit,$save);
			}
		}
		$response = substr($response,$headerSize);
		$json = json_decode($response,true);
		curl_close($curl);
		if $json['success'] == false) {
			return 'Invalid promoting permissions.';
		} else {
			$current = getRoleSet($ranks,$currentRank);
			$new = getRoleSet($ranks,$rank);
			return "Successfully changed rank of user $userId from ". $roles[$current] .' to '. $roles[$new] .'.'; // Details!
		}
	}
?>

**Comment by LukeTechnoUserOfficial** [comment]
Syntax error unexpected '[' Line 15

<?php
    /*

```
NOT MADE BY ME.
Source: http://php.net/manual/en/function.http-parse-headers.php#112917

If you are getting the X-CSRF token using pecl_http http_parse_headers function, do:
http_parse_headers['X-Csrf-Token'];
With this it's: 
http_parse_headers['X-CSRF-TOKEN'];

*/
if (!function_exists('http_parse_headers')) {
    function http_parse_headers ($raw_headers) {
        $headers = [];

        foreach (explode("\n", $raw_headers) as $i => $h) {
            $h = explode(':', $h, 2);

            if (isset($h[1])) {
                $headers[$h[0]] = trim($h[1]);
            }
        }

        return $headers;
    }
}
```

?>

**Comment by sentanos** [comment]
Is there really no way to upgrade your PHP version? Like I said, if you just do that everything should work fine.

Anyways the second error you are having is another incompatibility with old PHP versions, change the following line:

``` php
$headers = [];
```

to

``` php
$headers = array();
```

**Comment by LukeTechnoUserOfficial** [comment]
The highest it goes to is PHP 5.4? Is that good?

**Comment by LukeTechnoUserOfficial** [comment]
The final log just says 'No Change!' Did I do something wrong? I changed all of the json's like the first one you sent me in the misc file.

**Comment by LukeTechnoUserOfficial** [comment]
<?php
    // These are just a few miscellaneous ROBLOX APIs in php function form that you might want to use.
    function UsernameFromID($userId) {
        $json = json_decode(file_get_contents("http://api.roblox.com/users/$userId"),true);
        return $json['Username'];
    }
    function IDFromUsername($username) {
        $json = json_decode(file_get_contents("http://api.roblox.com/users/get-by-username?username=$username"),true);
        return $json['Id'];
    }
    function getRankInGroup($userId,$groupId) {
        return (int)simplexml_load_file("http://www.roblox.com/Game/LuaWebService/HandleSocialRequest.ashx?method=GetGroupRank&playerid=$userId&groupid=$groupId");
    }
    function fetchShout($cookie,$group) {
        // Log in for correct permissions
        $curl = curl_init("http://www.roblox.com/My/Groups.aspx?gid=$group");
        curl_setopt_array($curl,array(
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_COOKIEFILE => $cookie,
            CURLOPT_COOKIEJAR => $cookie
        ));
        $response = curl_exec($curl);
        curl_close($curl);
        $doc = new DOMDocument();
        $doc->loadHTML($response);
        return $doc->getElementById('ctl00_cphRoblox_GroupStatusPane_StatusTextField')->textContent;
    }
?>

**Comment by LukeTechnoUserOfficial** [comment]
The only problem i can think of is this being written wrong?

local baseURL = 'http://bwepromotions.hst.im' -- This is your website URL, NOT including the file.
local POSTKey = 'techno123775' -- Match with post key on your php file
local GETKey = 'luke123775' -- Match with get key on your php file
-- Example: baseURL/receiver.php?key=GETKey
-- {"Validate":POSTKey ...}

-- Action and parameters are based on what you put in the receiver php file.
local send = function(action,parameters)
    local array = {
        Validate = POSTKey,
        Action = action,
        Parameter1 = parameters[1],
        Parameter2 = parameters[2],
    }
    return game:GetService'HttpService':PostAsync(string.format('%s/receiver.php?key=%s',baseURL,GETKey),game:GetService'HttpService':JSONEncode(array))
end

-- MAKE SURE TO PUT PARAMETERS IN AN ARRAY, EVEN IF THERE IS ONLY ONE
--send('shout',{'KILLER IS BAD'})

script.Parent.Touched:connect(function(hit)
    local player = game.Players:GetPlayerFromCharacter(hit.Parent)
    send(player,'setRank',{player.userId,4})
    print(send(player,'setRank',{player.userId,4})) -- {player ID, RankRole}?
    print(player.Name.." has been promoted to Initiate.")
    player.PlayerGui.ScreenGui.End.Visible = true
    player.PlayerGui.ScreenGui.End.Script.Disabled = false
end)

**Comment by sentanos** [comment]
You are not being clear about the actual issue at this point and the issues you have had are your own. It has been concluded that this is not a problem with the scripts themselves but your server and setup, which is your responsibility only.

If you can create a clear concise issue with these scripts (that is, with relevant errors and pictures _after_ attempting to fix the problem on your own), even if it's related to your own setup, I will help simply out of the goodness of my heart. I am not providing service to you, I wrote these bots for anyone to use and I will deal with the problems of the scripts themselves so people who use it can continue to: I technically have no obligation to help anyone but I try to anyways. When people need step by step help over setup problems or post unclear issues there is nothing I can do for them.

Upgrade your PHP version and if you continue to have problems make a new issue _clearly outlying specifically what problems you are having_ after you have looked it up yourself and I will happily help.
