### ISSUE TITLE
Question more rather than an issue

### ISSUE THREAD

**Issue by colbert2677** [FroastJ/roblox-bots#24]
Where exactly do I configure the username and password? I did not see it in the receiver.php file, and I am unsure whether or not to edit the string or the $ var in the Includes/login.php file.

**Comment by sentanos** [comment]
You aren't looking hard enough, it's on [line 30](https://github.com/sentanos/roblox-bots/blob/master/Examples/receiver.php#L30).
Also, this is for issues, not questions. If you have questions please contact me directly.

**Comment by colbert2677** [comment]
Ah, thanks. Also, my bad, sorry.
