### ISSUE TITLE
FAILURE: Incorrect/missing validation key.

### ISSUE THREAD

**Issue by SamTheMan1456** [FroastJ/roblox-bots#28]
EVEN THOUGH IT'S RIGHT...

I keep getting this whenever I go to my website and click the reciever.php file.

**Comment by NNickey** [comment]
You need to include the 'two keys' in your url request.
Close this issue.

**Comment by SamTheMan1456** [comment]
What?

How do I do that?

**Comment by peterwilliamryan** [comment]
We need to know as it's for something.

**Comment by SamTheMan1456** [comment]
Please give me the format of how I do that.

**Comment by NNickey** [comment]
https://domain.domainextention/yourintention?key=yourkey
and in the post forum
{Validate=}
It's in the examples even.
https://github.com/sentanos/roblox-bots/tree/master/Examples
Again, please close this issue.

**Comment by SamTheMan1456** [comment]
http://rsf-panel.rf.gd/receiver.php?key=MYGETKEY{Validate=}

does not work..

**Comment by peterwilliamryan** [comment]
Please reply to him

**Comment by NNickey** [comment]
Are you not following the example that they provide..
Again..

CLOSE THIS ISSUE, ITS NOT AN ISSUE.

**Comment by NNickey** [comment]
And peterwilliamryan, you're not helping.

**Comment by peterwilliamryan** [comment]
Well he is my developer

**Comment by peterwilliamryan** [comment]
I hired him so we can have automatic ranking bot

**Comment by NNickey** [comment]
Then don't flood the issue and instead let the developer post as you have no role in Github.

**Comment by peterwilliamryan** [comment]
role?

**Comment by NNickey** [comment]
I'm not replying anymore as you won't listen.
Have fun with the support from others as this git is inactive.

**Comment by peterwilliamryan** [comment]
No don't I want it to be active

**Comment by peterwilliamryan** [comment]
I will listen all I want is auto somthing for roblox

**Comment by sentanos** [comment]
This got out of hand. Please review the documentation and related issues, also note as I have at the beginning of the README that this project is no longer maintained. Although it should still work, I am no longer responsible for fixing any bugs. Closed for being a duplicate of #10 and #3.

**Comment by peterwilliamryan** [comment]
?
