### ISSUE TITLE
Server replies that it 'Post $msg' but no message on wall.

### ISSUE THREAD

**Issue by NNickey** [FroastJ/roblox-bots#4]
![image](https://cloud.githubusercontent.com/assets/3466265/8888454/dd11bb2c-326a-11e5-9952-b0e7128d72e5.png)
![image](https://cloud.githubusercontent.com/assets/3466265/8888456/ed65840e-326a-11e5-8d3b-c9eb73b0d4dc.png)
Server replies that it had posted the message, but there is no message on group wall.

**Comment by sentanos** [comment]
Will investigate

**Comment by sentanos** [comment]
Post.php is confirmed to be working correctly, this is not an issue with the script itself but with your setup. Make sure that you have entered the correct credentials, that your player has wall posting permissions, that the rest of the setup is correct, and there are no errors on either side. You may also want to clear the saved cookies by deleting the "cookie" and cookieTime" files.

**Comment by NNickey** [comment]
I replaced the return error in login.php, found out its a Login Failure? How do I repair this, does this have something to do with the server not sending requests out? The password is right, and I was able to login normally. WAMP server.

**Comment by NNickey** [comment]
Found the issue why. WAMP Server does not like using https without any verification of the certificate.
Adding
"CURLOPT_SSL_VERIFYPEER => false"
to the curl_setopt_array allowed it to ignore the HTTPS certificate always.
Only temporary, I will not be using this setup, was only for testing..
