### ISSUE TITLE
Unable to send a userId Message..

### ISSUE THREAD

**Issue by NNickey** [FroastJ/roblox-bots#5]
Parse error: syntax error, unexpected '[' in 
/phpserv/Includes/getRoles.php on line 27

Same file as in github
https://github.com/FroastJ/roblox-bots/blob/master/Includes/getRoles.php

Trying to use message.php
![screenshot_41](https://cloud.githubusercontent.com/assets/3466265/8976190/caa8b2b2-3646-11e5-9f95-621f7492ac17.png)
![screenshot_42](https://cloud.githubusercontent.com/assets/3466265/8976215/1bdbd3a8-3647-11e5-9e98-3839971d297f.png)

**Comment by sentanos** [comment]
This is probably because you are using an outdated PHP version which is incompatible with certain syntax. You can correct it for your version by replacing the line with this:

``` php
$json = json_decode(file_get_contents("http://api.roblox.com/groups/$group"),true);
$roles = $json['Roles'];
```
