### ISSUE TITLE
Not logging in properly

### ISSUE THREAD

**Issue by PhoenixShay** [FroastJ/roblox-bots#6]
I was attempting to use this and after about an hour I got it to SOMEWHAT work. It would work and all... but it doesn't actually login. I can tell in the cookie file it's acting as a guest, and manually adding the ROBLOSECURITY does not help. The specified username and password are 100% correct.

Edit: Going into login.php, and changing the login failure return to die makes the response body "Login Failure! Error: "  Changing it back will make the error just pop up as "Invalid promoting permissions." 

I'd assume this is a problem with the login function. There is no captcha when I log in through my browser to the same account.

**Comment by NNickey** [comment]
Explaination of where you're hosting it from? If you're hosting from WampServer, there may be some issues. Where I got this WampServer info? "There is no captcha when I log in through my browser to the same account."

**Comment by PhoenixShay** [comment]
I'm using xampp to host it locally.And before you ask, yes, it's portforwarded correctly and so on.

**Comment by PhoenixShay** [comment]
YES! Oh my god, you're a lifesaver. The thing in your issue helped, adding the curl peer verify. Thank you so much!
