### ISSUE TITLE
Shout not working

### ISSUE THREAD

**Issue by wizwoz** [FroastJ/roblox-bots#9]
When I send a Post request, I get this back..

<br />
<b>Warning</b>:  curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in <b>/home/u593369978/public_html/roblox-bots-master/shout.php</b> on line <b>11</b><br />
<br />
<b>Fatal error</b>:  Call to a member function getAttribute() on a non-object in <b>/home/u593369978/public_html/roblox-bots-master/Includes/getPostArray.php</b> on line <b>18</b><br />

**Comment by sentanos** [comment]
Google is your friend.
Try turning off safe_mode in php.ini.

**Comment by wizwoz** [comment]
Using php 5.4, safe_mode removed?

**Comment by sentanos** [comment]
This is likely a problem with your host, not the scripts in the github.
Read this post to fix it: http://slopjong.de/2012/03/31/curl-follow-locations-with-safe_mode-enabled-or-open_basedir-set/
